config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :delivery_pages, only: :show
  resources :aquas, only: :show do
    resources :volumes, only: :index
    collection do 
      get 'check_price' => 'aquas#check_price'
    end
  end
  resources :prices, only: :index
  resources :coolers, only: [:index, :show] do
    collection do
      get 'get_image'
    end
  end
  resources :pomps, only: :index
  resources :accessories, only: :index
  resources :phone_calls, only: :create
  resources :services, only: :create
  resources :orders, only: :create
  resources :products, only: :index
  get 'profile' => 'welcome#profile'
  get 'profile/orders' => 'welcome#orders'
  get 'contacts' => 'welcome#contacts'
  get 'delivery' => 'welcome#delivery'
  get 'check_time' => 'welcome#check_time'
  get 'payment' => 'welcome#payment'
  get 'about' => 'welcome#about'
  get 'events' => 'welcome#events'
  get 'events/show/:id' => 'welcome#events_show', as: 'events/show'
  get 'service' => 'welcome#service'

  # 301 redirects
  get '/country',              to: redirect(URI.encode('/delivery_pages/4-Доставка%20питьевой%20воды%20в%20Ленобласти'), status: 301)
  get '/cat/coolers',          to: redirect('/coolers', status: 301)
  get '/cat/accessories',      to: redirect('/accessories', status: 301)
  get '/Peterburg',            to: redirect(URI.encode('/delivery_pages/5-Доставка%20воды%20в%20Санкт-Петербурге'), status: 301)
  get '/voda-v-ofis',          to: redirect(URI.encode('/delivery_pages/2-Доставка%20воды%20в%20офис'), status: 301)
  get '/schedule',             to: redirect('/delivery', status: 301)
  get '/skidki',               to: redirect('/events', status: 301)
  get '/dostavka',             to: redirect('/', status: 301)
  get '/cat/related_items',    to: redirect('/products/cups', status: 301)
  get '/voda-na-dom',          to: redirect(URI.encode('/delivery_pages/1-Доставка%20воды%20на%20дом'), status: 301)
  get '/price',                to: redirect('/prices', status: 301)
  get '/usloviya-dostavki',    to: redirect('/delivery', status: 301)
  get '/production',           to: redirect('/', status: 301)
  get '/schools',              to: redirect(URI.encode('/delivery_pages/3-Доставка%20воды%20в%20школы%20и%20детские%20сады'), status: 301)
  get '/o-vode/prima-aqua',    to: redirect('/aquas/1', status: 301)
  get '/o-vode/jodis',         to: redirect('/aquas/4', status: 301)
  get '/primaaqua',            to: redirect('/aquas/1', status: 301)
  get '/zakaz-dostavka-vody',  to: redirect('/', status: 301)
  get '/o-vode/legenda-gor',   to: redirect('/aquas/2', status: 301)

  root 'welcome#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '*path' => redirect('/')  unless Rails.env.development?
end

app/models/accessory.rb
class Accessory < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/aqua.rb
class Aqua < ActiveRecord::Base
  has_many :aqua_posts
  has_many :docs
  has_many :prices
  has_many :volumes

  default_scope -> { order(:id) }

  def to_params
    "#{id}-#{name}"
  end
end

app/models/aqua_post.rb
class AquaPost < ActiveRecord::Base
  belongs_to :aqua
  mount_uploader :image, ImageUploader

  default_scope -> { order(position: :asc) }
end

app/models/article.rb
class Article < ActiveRecord::Base
  self.inheritance_column = nil
  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/company_post.rb
class CompanyPost < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/cooler.rb
class Cooler < ActiveRecord::Base
  has_and_belongs_to_many :tags
  has_many :images, as: :imageable, dependent: :destroy

  def has_tag?(name)
    tags.where(name: name).any?
  end

  def image_url(version)
    images.first.name_url(version) if images.first.present?
  end

  def type
    'Кулер'
  end
end

app/models/district.rb
class District < ActiveRecord::Base
  validates_presence_of :name
  after_save :set_coord

  def self.search(search)
    if search
      where('lower(name) LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end

  private
  def set_coord
    if self.lat.blank? && self.lon.blank?
      url = "http://geocode-maps.yandex.ru/1.x/?format=json&geocode=#{self.name.split.join('+')}&ll=30.327541,59.936952&spn=2,2&rspn=1"
      response = JSON.parse(Net::HTTP.get_response(URI.parse(URI.encode(url))).body)
      self.lon, self.lat = if response['response']['GeoObjectCollection']['featureMember'].present?
                       response['response']['GeoObjectCollection']['featureMember'][0]['GeoObject']['Point']['pos'].split
                     else
                       [0,0]
                     end
      self.save
    end
  end
end

app/models/doc.rb
class Doc < ActiveRecord::Base
  mount_uploader :name, FileUploader
  belongs_to :aqua
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :name, ImageUploader
  belongs_to :imageable, polymorphic: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  after_commit :mail, on: :create

  private
  def mail
    NoticeMailer.product(self).deliver
  end
end

app/models/phone_call.rb
class PhoneCall < ActiveRecord::Base
  after_commit :mail, on: :create

  private
  def mail
    NoticeMailer.call(self).deliver
  end
end

app/models/pomp.rb
class Pomp < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :aqua
  belongs_to :volume

  default_scope -> { order(:start_count) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :category

end

app/models/service.rb
class Service < ActiveRecord::Base
  after_commit :mail, on: :create

  private
  def mail
    NoticeMailer.service(self).deliver
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :coolers
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum customer_type: [:individual, :company]

  def company?
    customer_type == 'company'
  end

  def individual?
    customer_type == 'individual'
  end
end

app/models/volume.rb
class Volume < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :aqua
  has_many :prices

  default_scope -> { order(value: :desc) }

  def value_str
    if value < 3.0
      :small
    elsif value > 10.0
      :big
    else
      :medium
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    aqua = Aqua.first
    gon.price_19 = aqua.prices.where(volume_id: aqua.volumes.where(value: 19).first).pluck(:value).min
    gon.price_8 = aqua.prices.where(volume_id: aqua.volumes.where(value: 8).first).pluck(:value).min
    gon.price_6 = aqua.prices.where(volume_id: aqua.volumes.where(value: 6).first).pluck(:value).min
    gon.price_1 = aqua.prices.where(volume_id: aqua.volumes.where(value: 0.6).first).pluck(:value).min
  end

  def contacts; end

  def payment; end

  def profile
    redirect_to root_path unless current_user
  end

  def orders
    if current_user
      @orders = current_user.orders.order(created_at: :desc)
    else
      redirect_to root_path
    end
  end

  def about
    @posts = CompanyPost.all
  end

  def delivery
    @district = District.search(params[:name])
    gon.district = @district.select(:lon, :lat)
    @district = @district.order(:name).group_by{|u| u.name[0]}
  end

  def events
    @articles = Article.order(id: :desc)
    @articles = @articles.where(type: params[:type]) if params[:type].present?
  end

  def events_show
    @event = Article.find(params[:id])
  end

  def check_time
    render json: OrderService.check_date(params[:data])
  end

  def service
  end
end

app/views/welcome/_company_post.html.haml
.post
  .post_image
    = image_tag post.image_url((:background if post.image.version_exists?(:background)))
    .post_text{ style: "color: white" }
      .post_text__header
        = post.title
      .post_text__body
        = post.description

app/views/welcome/_events_article.html.haml
.article
  - if article.image.present?
    .article-image
      = image_tag article.image_url(:medium)
  .article-body
    .article-body-title
      = article.title
    .article-body-desc
      = article.grow_descript

app/views/welcome/_events_news.html.haml
.news
  .news-info
    #{info}, #{Russian::strftime(news.created_at, '%e %B %Y')}
  .news-title
    = news.title
  - if news.image.present?
    .news-image
      = image_tag news.image_url(:medium)
  .news-desc
    = news.grow_descript
  - if news.type == 'article'
    .news-link_show
      = link_to 'Подробнее', events_show_path(news.id)

app/views/welcome/_list_district.html.haml
- district.each do |distr, items|
  - items.each do |item|
    = link_to item.name, '#', popup: item.popup
    - if item.str
      = image_tag 'star.png'
    %br
  %br

app/views/welcome/_order.html.haml
.order__item
  %tr
    %td
      = order.id
    %td
      = order.delivery_date
    %td
      = order.delivery_time
    %td
      = order.customer_comment
    %td
      = products_list(order).html_safe

app/views/welcome/_profile_menu.html.haml
.profile_menu
  = link_to 'Заказы', '/profile/orders'
  = link_to 'Профиль', '/users/edit'

app/views/welcome/about.html.haml
- title 'Группа компаний Мир Воды. О компании: как мы работаем, наши ценности и сотрудники'
- meta_description 'У нас Вы можете заказать воду с доставкой Санкт-Петербург и Ленинградская область'
- meta_keywords 'заказ воды, доставка воды, Prima-Aqua, прима аква, питер, Санкт-Петербург, спб'
= render 'layouts/fixed_header'

//.aqua_posts
//  - @posts.each do |post|
//    = render 'welcome/company_post', post: post
//  .clearfix

.default_about
  Страница в разработке

app/views/welcome/contacts.html.haml
- title 'Контакты офиса и производства. Группа компаний Мир Воды: Акваплюс, Акваполюс, Лидер-Аква'
- meta_description 'Контактные данные Prima-Aqua. Телефон. Адрес'
- meta_keywords 'контактные данные, телефон, адрес'
= javascript_include_tag 'http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU'
.contacts-body
  .contacts-body-title
    Контакты
  #contacts-body-map
  .contacts-body-blocks
    .contacts-body-blocks-item
      .contacts-body-blocks-item-title
        .contacts-body-blocks-item-title-img
          = image_tag 'item_office.png'
        .contacts-body-blocks-item-title-text
          Офис
      .contacts-body-blocks-item-body
        .contacts-body-blocks-item-body-text
          Тел.: (812) 335-40-80
          %br
          Горячая линия.: 93-110-93
          %br
          195248, г. Санкт-Петербург, ул. Партизанская, д.25
          %br
          Эл. почта:
          %span info@prima-aqua.ru
    .contacts-body-blocks-item
      .contacts-body-blocks-item-title
        .contacts-body-blocks-item-title-img
          = image_tag 'item_prod.png'
        .contacts-body-blocks-item-title-text
          Производство
      .contacts-body-blocks-item-body
        .contacts-body-blocks-item-body-text
          Ленинградская область,
          %br
          Поселок Стеклянный



:javascript
  ymaps.ready(init);
  function init () {
    var myMap = new ymaps.Map('contacts-body-map', {
      center: [60.230488, 30.302889],
      zoom: 7.7
      }),
      office = new ymaps.Placemark([59.969037, 30.367005], {
        hintContent: ''
      }, {
        // Опции.
        // Необходимо указать данный тип макета.
        iconLayout: 'default#image',
        // Своё изображение иконки метки.
        iconImageHref: '/assets/office.png',
        // Размеры метки.
        iconImageSize: [30, 42],
        // Смещение левого верхнего угла иконки относительно
        // её "ножки" (точки привязки).
        iconImageOffset: [-3, -42]
      }),
      prod = new ymaps.Placemark([60.3840644, 30.2405383], {
        hintContent: ""
      }, {
        // Опции.
        // Необходимо указать данный тип макета.
        iconLayout: 'default#image',
        // Своё изображение иконки метки.
        iconImageHref: '/assets/prod.png',
        // Размеры метки.
        iconImageSize: [30, 42],
        // Смещение левого верхнего угла иконки относительно
        // её "ножки" (точки привязки).
        iconImageOffset: [-3, -42]
      });

    myMap.geoObjects.add(office);
    myMap.geoObjects.add(prod);
    myMap.controls.add("zoomControl");
  }

app/views/welcome/delivery.js.erb
$('.delivery-body-text-list').html("<%= escape_javascript render(:partial => 'list_district', locals: { district: @district }) %>");
$('#delivery-body-map').empty();

app/views/welcome/events.html.haml
- title 'Новости, события и акции. Группа компаний Мир Воды - доставка воды на дом и в офис'
- meta_description 'События Prima-Aqua'
- meta_keywords 'события, новости'
.events-title
  События
.events-filters
  .events-filters-item
    = link_to 'Все', events_path
  .events-filters-item
    = link_to 'Акции', events_path(type: 'promotion')
  .events-filters-item
    = link_to 'Новости', events_path(type: 'news')
  .events-filters-item
    = link_to 'Статьи', events_path(type: 'article')
.events-items
  - @articles.each do |item|
    - if item.type == 'promotion'
      = render 'welcome/events_article', article: item
    - elsif item.type == 'news' || 'article'
      - info = item.type == 'news' ? 'НОВОСТИ' : 'СТАТЬИ'
      = render 'welcome/events_news', news: item, info: info

app/views/welcome/orders.html.haml
- title 'Prima aqua - доставка воды Санкт-Петербург и Ленинградская область. Заказы'
- meta_description 'Заказ воды'
- meta_keywords 'заказать воду, заказ, купить воду'
.profile
  = render 'profile_menu'

  %h2 Мои заказы
  %table
    %tr
      %th
        Код заказа
      %th
        Дата доставки
      %th
        Время доставки
      %th
        Комментарий
      %th
        Товары

    - @orders.each do |order|
      = render 'order', order: order

app/views/welcome/payment.html.haml
- title 'Способы оплаты при заказе воды на дом или в офис'
- meta_description 'Оплата заказа'
- meta_keywords 'виза, мастер кард, процесс оплаты'
.payment_page
  .payment_page__header
    Оплата для физических лиц

  -#.payment_page__title
  -#  Принимаем к оплате карты
  -#.payment_page__text
  -#  = image_tag image_url('cards.png')

  .payment_page__title
    Оплата наличными.
  .payment_page__text
    Оплата производится курьеру при получении товара

  .payment_page__title
    По банковской карте.
  .payment_page__text
    В нашей работе мы используем программу и картридеры 2can, с помощью них Вы сможете оплатить Ваш заказ при получении с помощью банковской карты. К сожалению, в данный момент не все наши экипажи оснащены необходимыми устройствами, поэтому возможность оплаты по картам присутствует не на всех маршрутах

  %br
  .payment_page__header
    Оплата для юридических лиц

  .payment_page__title
    По безналичному счету.
  .payment_page__text
    Оплата осуществляется только после заключения договора.

  .payment_page__title
    Оплата наличными.
  .payment_page__text
    Оплата производится курьеру при получении товара

app/views/welcome/profile.html.haml
- title 'Prima aqua - доставка воды Санкт-Петербург и Ленинградская область. Профиль'
- meta_description 'Профиль пользователя'
- meta_keywords 'личный кабинет, профиль'
.profile
  = render 'profile_menu'
  профиль пользователя

app/views/welcome/service.html.haml
- title 'профилактика, санитарная обработка кулеров, водного оборудования с выездом мастера'
- meta_description 'Заказ обслуживания'
- meta_keywords 'сервис, облуживание, заказать'
.service
  .service-title
    Обслуживание кулеров
  .service-body_imgs
    .service-body_imgs-body
      Некоторые считают, что обслуживание кулера для воды – это своевременная замена бутылей и забота об их достаточном запасе. На самом деле кулеры, как любая сложная техника, требуют специального ухода: санитарной обработки (профилактики), иногда ремонта. Специфика «запущенных» кулеров – ломкость и привкус. Срок эксплуатации машины зависит от качества бензина, а кулера – от качества воды и регулярного обслуживания.
    .service-body_imgs-img
      = image_tag 'service.png'
      .service-body_img-button
        = link_to 'Заказать обработку кулера', '#'
  .service-body
    .service-body-title
      Санитарная обработка кулера
    .service-body-text
      Минерализация, являясь одной из ключевых характеристик воды, определяет количество солей, растворенных в ней. В процессе эксплуатации кулерных установок часть имеющихся в воде солей оседает на их нагревательных элементах, образуя осадок в виде накипи, который увеличивает время нагрева воды, придает ей неприятный привкус и формирует пленку или осадочный слой на дне стакана.
      %br
      %br
      Кроме того, растворенные в воде минеральные соли оказывают неблагоприятное воздействие и на другие элементы кулеров. В результате такого воздействия могут, например, получить повреждения эластичные уплотнители, негерметичность которых становится причиной протечек трубок и проблем с закрыванием кранов.
      %br
      %br
      Санитарная обработка кулерного оборудования может потребоваться и в случае проникновения внутрь аппарата различного рода загрязнений и бактерий. Подобное возможно при несоблюдении гигиенических норм установщиками бутылей и ведет к быстрому размножению бактерий и возникновению на внутренних поверхностях аппарата слизистых масс.
      %br
      %br
      Несомненно, что подобного рода бактериальное «заражение» не только портит качество воды и отрицательным образом влияет на ее вкусовые свойства, но и может оказать вредное воздействие на здоровье тех, кто употребляет воду из такого аппарата. Для предотвращения подобного рода ситуаций важно в регулярном режиме производить профилактику кулеров (дезинфекция кулеров).
      %br
      %br
      Следует отметить, что возникновение загрязнений может произойти и в случае, когда при установке емкостей с водой не снимаются термоусадочные колпачки или наклейки, находящиеся на пробке. В такой ситуации части пленочного или бумажного материала оказываются внутри аппарата, образуют затор в трубке, в результате которого вода перестанет поступать в нужном направлении. Это, как правило, приводит к перегреву кулерной установки и выходу из строя ее нагревательных элементов и электронных устройств.
      %br
      %br
      Еще одной распространенной причиной поломок кулеров является использование водопроводной воды для заливки в ее аппарат. Обладая высокой концентрацией солей, которая во много раз превышает аналогичные параметры воды бутилированной, вода из-под крана очень быстро образует критическую дозу накипи и выводит кулер из строя. Кроме того, механические и вредоносные примеси, содержащиеся в водопроводной воде – частицы песка, различного рода бактерии - также способствуют быстрой поломке или бактериальному загрязнению кулерных установок.
      %br
      %br
      Важно! В стандартном режиме эксплуатации необходимо осуществлять дезинфекционные работы не реже одного раза каждые полгода. В случае максимальной загруженности аппарата, его профилактическую санитарную обработку следует проводить ежеквартально.
      %br
      %br
      Регулярные санитарно-профилактические мероприятия и дезинфекция кулерных установок – это экономичный метод сохранения высокого качества, приятного вкуса бутилированной воды и ее безопасности.
      %br
      %br
      В ПРОГРАММУ КОМПЛЕКСНОЙ САНИТАРНОЙ ОБРАБОТКИ КУЛЕРНЫХ УСТАНОВОК включены:
      %br
      промывка наружных поверхностей аппарата;
      %br
      промывка горлышка бутыля и устройства подачи воды (кранов),
      %br
      а также полная очистка:
      %br
      нагревательных элементов от имеющейся накипи;
      %br
      внутренних систем, элементов и узлов от любых загрязнений;
      %br
      и полная антибактериальная обработка кулера.
      %br
      Стоимость всего комплекса работ составляет 950 рублей.


    -#.service-body-img
    -#  = image_tag 'gears.png'
    -#.service-body-text


.modal_area
  .modal__back.js_modal_back
  .modal__view
    = render 'layouts/service_modal'